[project]
name = "fastapi-oauth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.135.1",
    "httpx>=0.28.1",
    "ipython>=9.11.0",
    "pwdlib[argon2]>=0.3.0",
    "pydantic>=2.12.5",
    "pyjwt>=2.11.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.5",
]
